config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

  resources :entries

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	# This gives us server-side validation
	validates :name, presence: true, length: { minimum: 3 }
	validates :description, presence: true, length: { minimum: 10 }
	validates :ingredients, presence: true, length: { minimum: 10 }
	validates :instructions, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	# Allows a very basic authentication scheme.
	#http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show, :new, :create]

	# New function. Creates a new "Entry" instance
	def new
		@entry = Entry.new
	end
	
	# Shows the proper Entry that matches the id
	def show
		@entry = Entry.find(params[:id])
	end
	
	# Creates a new entry with the params it's sent
	def create
		@entry = Entry.new(entry_params)

		# If it went fine, redirect to its show page, otherwise go back to the new page
		if @entry.save
			redirect_to @entry
		else
			render 'new'
		end
	end

	# Loads the right entry for the edit page. DEPRECATED
	def edit 
		@entry = Entry.find(params[:id])
	end
	
	# Updates the entry based on the params it is sent
	def update
	  @entry = Entry.find(params[:id])
	 
	 # If everything is correct, go to show. Otherwise, go back to edit
	  if @entry.update(entry_params)
		redirect_to @entry
	  else
		render 'edit'
	  end
	end
	
	# Loads the "entries" variable with all current entries
	def index
		@entries = Entry.all
	end
	
	# Deletes an entry (with the right permissions)
	def destroy
	  @entry = Entry.find(params[:id])
	  @entry.destroy
	  redirect_to entries_path
	end
	
	private
		# Constrains the types and names of the params it's sent
		def entry_params
			params.require(:entries).permit(:name, :description, :ingredients, :instructions)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<!--
Edit file. Linked to in the show page.

Allows editing of entry with the right basic authentication.
-->

<h3 class="text-center">Edit Recipe</h1>

<div class="entry center">
<%= form_for :entries, url: entry_path(@entry), method: :patch do |f| %>
		<p>
			<%= f.label :name %><br>
			<%= f.text_field(:name, :value => @entry.name) %>
			
		</p>

		<p style="width: 100%;">
			<%= f.label :description %><br>
			<%= f.text_area(:description, :value => @entry.description) %>
		</p>

		<p>
			<%= f.label :ingredients %><br>
			<%= f.text_area(:ingredients, :value => @entry.ingredients) %>
		</p>

		<p>
			<%= f.label :instructions %><br>
			<%= f.text_area(:instructions, :value => @entry.instructions) %>
		</p>
		
		<% if @entry.errors.any? %>
			<div id="error_explanation">
				<h3><%= pluralize(@entry.errors.count, "error") %> prohibited this recipe from being saved:</h3>
				<ul>
					<% @entry.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div>
			<%= button_tag 'Cancel', :type => 'button', :class => 'cancel float-right', :onclick => "if(confirm('Are you sure you want to cancel changes?')) { location.href = '#{entry_path(@entry)}' } else { return false; }" %>
			<%= f.submit "Update Recipe", :class => 'float-right'%>
			<br/>
		</div>
	<% end %>
	
</div>

<div class="text-center">
	<span class="links"><%= link_to 'Go back to Home', entries_path %></span>
</div>

app/views/entries/index.html.erb
<!--
Index file. Serves as the home page for our project.
-->
<div id="intro" class="center">
	<p>
	This is a repository for recipes. You can add recipes to the database, edit existing ones, or delete them as well.
	</p>
</div>

 <div class="center half-width">
	<%= button_to 'Add a New Recipe', new_entry_path, :method => :get, :class => 'float-right' %>
</div>

<div id="indexheader" class="center">
	<h3>Recipes Index:</h3>
</div>

<div class="list">
  <% @entries.each do |entry| %>
	<div class="entry center">
    <p>
      <label><b>Recipe Name: </b></label><em><%= entry.name %></em>
    </p>
	<p>
		<label><b>Description: </b></label><%= entry.description %>
	</p>

	<p class="links">
		<%= link_to "Show me this Recipe...", entry_path(entry) %>
	</p>
	</div>
  <% end %>
</div>

app/views/entries/new.html.erb
<!--
New file.

Allows the entry of new recipes by users.
-->

<h3 class="text-center">Add a New Recipe</h1>

<div class="entry center">
<%= form_for :entries, url: entries_path do |f| %>
		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>

		<p style="width: 100%;">
			<%= f.label :description %><br>
			<%= f.text_area :description %>
		</p>

		<p>
			<%= f.label :ingredients %><br>
			<%= f.text_area :ingredients %>
		</p>

		<p>
			<%= f.label :instructions %><br>
			<%= f.text_area :instructions %>
		</p>
		
		<% if @entry.errors.any? %>
			<div id="error_explanation">
				<h3><%= pluralize(@entry.errors.count, "error") %> prohibited
				  this recipe from being saved:</h3>
				<ul>
					<% @entry.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div>
			<%= button_tag 'Cancel', :type => 'button', :class => 'cancel float-right', :onclick => "if(confirm('Are you sure you want to cancel changes?')) { location.href = '#{entries_path()}' } else { return false; }" %>
			<%= f.submit "Save Recipe", :class => 'float-right' %> 
			<br/>
		</div>
	<% end %>
	
</div>

<div class="text-center">
	<span class="links"><%= link_to 'Go back to Home', entries_path %></span>
</div>

app/views/entries/show.html.erb
<!--
Show file. Linked to the recipes displayed on the front page.

Shows all the data associated with each recipe (entry).
-->

<h3 class="text-center"><%= @entry.name %></h1>

<div class="entry center"> 
	<p>
	  <h3><strong>Description:</strong></h3>
	  <%= @entry.description %>
	</p>

	<hr/>
	<p>
	  <h3><strong>Ingredients:</strong></h3>
	  <%= @entry.ingredients %>
	</p>

	<hr/>
	<p>
	  <h3><strong>Instructions:</strong></h3>
	  <%= @entry.instructions %>
	</p>
</div>

<div class="text-center">
	<p class="links"><%= link_to 'Edit this Recipe', edit_entry_path(@entry) %> | <%= link_to 'Delete this Recipe', entry_path(@entry),
                    method: :delete, data: { confirm: 'Are you sure you want to delete this recipe? This cannot be undone.' } %>
	</p>
	<p class="links"><%= link_to 'Go back to Home', entries_path %></p>
	
</div>

app/views/layouts/_footer.html.erb
<!--
Footer start.
-->

<br/>

<hr/>
<p>
	CS 4540 - Ruby On Rails Project
</p>
<p>
	David Onken and John Chase
</p>

<!--
Footer end.
-->

app/views/layouts/_header.html.erb
<!--
Header start.
-->

<h1 class="text-center">
<a class="nolink" href="<%= entries_path %>">The Recipe Repo</a>
</h1>

<h2 class="text-center">
	<em>
		<a class="nolink" href="<%= entries_path %>">
			<%= headers = ["If we are what we eat, then I am cheap, fast, and easy (and greasy)!",
			"Even better than GitHub!",
			"If I had a snarky comment, it would go here!",
			"Committing changes has never been so delicious!",
			"Segmentation fault",
			"Recipes, ruby, and rails",
			"We spent hours making up these headers.",
			"Reticulating splines!",
			"Now in perpetual Beta!",
			"Much header. So dynamic.",
			"Praise the sun! (Dark Souls meme)",
			"We'll have Mercurial support one day!",
			"No ads!",
			"All the important food groups! Probably...",
			"Why did I even write all these headers?",
			"404! Just kidding.",
			"<h4>Headerception</h4>",
			"This is the last header, I promise!"]
			#Get a random header from the list
			headers[rand(headers.length)]  %>
		</a>
	</em>
</h2>

<hr/>

<!--
Header End
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--
Ruby Project by David Onken and John Chase
-->

<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>